name: elmulator
base: core20
version: '2.4.0'
summary: Simplifies electrical calculations and optimizes circuit distribution.
description: |
  This app provides essential calculations related to resistance, impedance, and circuit distribution.

  Rings Resistance Calculations:
  Calculate resistance values for various scenarios by inputting resistance values and reviewing calculated outputs in real-time.

  External Impedance Calculations:
  Determine impedance in kilo-amperes based on provided voltage and impedance values, with the option for default values for missing inputs.

  Module for Calculating Circuit Count:
  Streamline the distribution of circuit work among engineers by inputting the number of engineers and circuits, and the app calculates the optimal distribution for single-phase and three-phase circuits.

  TI Rename Tool:
  Automate renaming of thermal imaging photos by matching <NAME> TI-<REF> lines from a PDF with photo filenames, supporting both dry-run previews and apply mode for in-place renaming or copying to an output folder.

  Issues to Excel Extraction - EML (emergency lights):
  Extract issue descriptions from a PDF by parsing the second line of each page, preview planned outputs in dry-run mode, and generate an Excel file with all issues when applying.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: nil
